### ISSUE TITLE
Cool way to build the DB

### ISSUE THREAD

**Issue by oliverjam** [fac19/week6-Tiger-Kingdom#48]
https://github.com/fac19/week6-Tiger-Kingdom/blob/218115b3f2ef0cdf87c3aa62656232fd44cda92d/src/db/build.js#L12

I hadn't seen this before, it's pretty cool. Does it let you both import the build function in your tests and run this file directly with node?

**Comment by Roger-Heathcote** [comment]
Yep. It's so we can initialise the db by running npm run setupdb
